[package]
name = "client_example"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = "0.32.0"
subxt-signer = { version = "0.32.0", features = ["subxt"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time"] }

[workspace]
